"""
DevRecAI Markdown Report Builder.

Renders professional Markdown reports using Jinja2 templates.
"""
from __future__ import annotations

import asyncio
from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Environment, BaseLoader

from devrecai.config.settings import get_settings

REPORT_TEMPLATE = """\
# DevRecAI Report — {{ project_name }}

> Generated: {{ date }}  |  Scorer Mode: {{ scorer_mode }}  |  Tools Evaluated: {{ tool_count }}

---

## Executive Summary

This report provides AI-powered DevOps tool recommendations for the **{{ project_name }}** project.
Based on your team profile and requirements, DevRecAI has evaluated {{ tool_count }} tools across
{{ category_count }} categories and selected the best matches for your specific context.

---

## Project Profile

| Field | Value |
|-------|-------|
| Project Type | {{ profile.project_type | default('N/A') }} |
| Team Size | {{ profile.team_size | default('N/A') }} |
| DevOps Maturity | {{ profile.devops_maturity | default('N/A') }} |
| Budget Tier | {{ profile.budget_tier | default('N/A') }} |
| Cloud Provider(s) | {{ profile.cloud_provider | join(', ') if profile.cloud_provider else 'N/A' }} |
| Languages | {{ profile.languages | join(', ') if profile.languages else 'N/A' }} |
| Deployment Style | {{ profile.deployment_style | default('N/A') }} |
| Uptime SLA | {{ profile.uptime_requirement | default('N/A') }}% |
| Compliance | {{ profile.compliance | join(', ') if profile.compliance else 'None' }} |

**Pain Points:**
{{ profile.pain_points | default('Not specified') }}

---

## Recommended Toolchain

{% for category, tools in categories.items() %}{% if tools %}
### {{ category }}

| Rank | Tool | Score | Confidence | Fit |
|------|------|-------|------------|-----|
{% for tool in tools[:5] %}| #{{ loop.index }} | **{{ tool.name }}** | {{ tool.score }}/100 | {{ tool.confidence }} | {{ tool.fit_tag }} |
{% endfor %}
{% endif %}{% endfor %}

---

## Tool Justifications (AI-Generated)

{% for tool_name, expl in explanations.items() %}
### {{ tool_name }}

**Fit Summary:** {{ expl.fit_summary | default('N/A') }}

**Integration Notes:** {{ expl.integration_notes | default('N/A') }}

**Risks:** {{ expl.risks | default('N/A') }}

**Maturity Required:** {{ expl.maturity_required | default('N/A') }}

**Confidence:** {{ expl.confidence_level | default('MEDIUM') }}

---
{% endfor %}

## Risk Register

| Risk | Category | Severity | Mitigation |
|------|----------|----------|------------|
| Vendor lock-in from commercial tools | Strategic | Medium | Prefer OSS alternatives where score delta < 10 |
| Learning curve impact on velocity | People | Medium | Pilot with 1 category first |
| API key / credential management | Security | High | Use Vault or AWS Secrets Manager from day 1 |
| Tool sprawl | Operational | Low | Adopt max 1-2 tools per category |

---

## Implementation Roadmap

### Phase 0 (Days 0-30): Foundation
- Set up chosen CI/CD pipeline
- Establish secrets management baseline
- Configure basic observability

### Phase 1 (Days 30-60): Core Stack
- Deploy IaC tooling
- Integrate security scanning into CI/CD
- Add centralized logging

### Phase 2 (Days 60-90): Maturity
- Enable full observability stack
- Implement GitOps workflows
- Add cost monitoring

---

## Cost Estimate

This estimate is indicative based on team size and selected tools.

| Tier | Monthly Cost |
|------|-------------|
| Open-source only | $0 (infra costs only) |
| Low budget baseline | $200-800/mo |
| Medium stack | $1,000-5,000/mo |
| Enterprise full stack | $10,000+/mo |

---

## Next Steps

1. Review recommendations with your team
2. Pilot the top CI/CD and Observability tools in a staging environment
3. Run `devrec feedback --session {{ session_id }}` after 30 days to rate outcomes
4. Run `devrec train` after collecting 50+ feedback entries to improve ML recommendations

---

*Report generated by DevRecAI v1.0.0 — AI-powered DevOps tool recommendation engine*
"""


class MarkdownExporter:
    """Jinja2-based Markdown report builder."""

    def __init__(self) -> None:
        self._settings = get_settings()
        self._env = Environment(loader=BaseLoader())

    async def export(
        self,
        session_data: dict,
        output_dir: Optional[Path] = None,
    ) -> str:
        """
        Generate and save Markdown report.
        Returns the path to the saved file.
        """
        profile = session_data.get("profile_json", {})
        results = session_data.get("results_json", {})
        project_name = profile.get("project_name", "report")
        session_id = session_data.get("session_id", "unknown")

        categories = results.get("categories", {})
        explanations = results.get("explanations", {})
        tool_count = results.get("metadata", {}).get("tool_count", 0)

        template = self._env.from_string(REPORT_TEMPLATE)
        content = template.render(
            project_name=project_name,
            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            scorer_mode=results.get("metadata", {}).get("mode", "rule_based"),
            tool_count=tool_count,
            category_count=len(categories),
            profile=profile,
            categories=categories,
            explanations=explanations,
            session_id=session_id,
        )

        # Determine output path
        if output_dir is None:
            output_dir = Path(self._settings.output.directory).expanduser()
        output_dir.mkdir(parents=True, exist_ok=True)

        date_str = datetime.now().strftime("%Y-%m-%d")
        slug = project_name.lower().replace(" ", "_").replace("/", "-")
        filename = f"{date_str}_{slug}_DevRecAI_Report.md"
        filepath = output_dir / filename

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        return str(filepath)
